name: Test Workflow Automatique

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-automation:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupération du dépôt
        uses: actions/checkout@v4

      - name: 2. Vérification de l’environnement
        run: |
          echo "Le runner GitHub est prêt."
          node -v
          python --version

      - name: 3. Simulation des tests QA
        run: |
          echo "Lancement des tests automatisés..."
          sleep 5
          echo "Résultat : Tous les tests sont au vert ✅"
